config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'sessions/new'

  resources :blogs
  get '/news', to: "blogs#index"
  get '/news/:id', to: "blogs#show", as: "new"
  get '/new_news', to: "blogs#new"
  get '/news/:id/edit', to: "blogs#edit", as: "edit_news"
  put '/news/:id/update', to: "blogs#update"
  get '/news_management', to: "blogs#management"
  post '/news/:id/toggle', to: "blogs#toggle_active"
  resources :static_pages, :only => [:index, :edit, :create, :update]
  get 'home', :to => 'static_pages#home'
  get 'home/edit', :to => 'static_pages#edit_home'
  get 'about_us', :to => 'static_pages#about_us'
  get 'about_us/edit', :to => 'static_pages#edit_about_us'
  get 'woofs_for_help', :to => 'static_pages#woofs_for_help'
  get 'woofs_for_help/edit', :to => 'static_pages#edit_woofs_for_help'
  get 'help', :to => 'static_pages#help'
  get 'help/edit', :to => 'static_pages#edit_help'
  get 'contact_us', :to => 'static_pages#contact_us'
  get 'contact_us/edit', :to => 'static_pages#edit_contact_us'
  post 'contact', to: 'forms#contact'
  get 'foster', to: 'static_pages#foster'
  get 'foster/edit', to: 'static_pages#edit_foster'
  get 'event/edit', to: 'static_pages#edit_event'
  get 'special_event/edit', to: 'static_pages#edit_special_event'
  get 'donate', to: 'static_pages#donate'
  get 'donate/edit', to: 'static_pages#edit_donate'
  get 'adopt/edit', to: 'static_pages#edit_adopt'
  get 'edit_sidebar', :to => 'static_pages#edit_sidebar'
  resources :events
  get 'special_events', :to => "events#special_events"
  get 'adopt', :to => "forms#adopt"
  post 'send_adoption', :to => "forms#send_adoption"
  resources :users
  get '/user/:id/user_management', to: 'users#hierarchy'
  post '/user/:id/user_management', to: 'users#set_hierarchy'
  post '/users/set_state', to: 'users#set_state'
  get 'confirm_email', to: 'users#confirm_email'
  post '/user/:id/ban', to: 'users#ban', as: 'ban_user'
  resources :comments
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/confirm_email_login', to: 'sessions#confirm_email_login'
  delete '/logout', to: 'sessions#destroy'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :password_managements, only: [:create, :edit, :update]
  root to: 'static_pages#home'

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
    validates :about_us, presence: true
    validates :home_block_one, presence: true
    validates :help, presence: true
    validates :contact_us, presence: true
    validates :sidebar, presence: true
    validates :woofs_for_help, presence: true
    validates :event, presence: true
    validates :special_event, presence: true
    validates :adopt, presence: true
    validates :foster, presence: true
    validates :donate, presence: true
    before_create :one_sp_record

    private
        def one_sp_record
            true
            if StaticPage.all.count > 0
                false
            end
        end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include ApplicationHelper
  require 'will_paginate/array'
  before_action :set_sp
  before_action :set_static_page, only: [:show, :edit, :update, :destroy]
  before_action :has_access_admin, except: [:home, :about_us, :woofs_for_help, :foster, :donate, :adopt, :event, :special_event, :help, :contact_us]

  #Editable Pages
   
  def home
    @debug = params
    params.each do |k, v|
        puts "#{k} : #{v}"
    end
    @homeblockone = StaticPage.first.home_block_one
#parse XML
    url = "http://api.adoptapet.com/search/pets_at_shelter?key=56f8d6ec5a75c3a28c5893fad35d250f&shelter_id=82425"
    uri = URI(url)
    response = Net::HTTP.get(uri)
    @hash = Hash.from_xml(response) 
    @order= @hash["result"]["pets"]
    @details_hash = {}
    @pets = @order.sort_by { |k| k["pet_name"] }
    @pets.each_with_index do |pet, i|
#url format http://www.adoptapet.com/pet/PET_ID-PET_CITY-PET_STATE-PET_PRIMARY_BREED-MIX
#apparently only the ID makes the URL work. so we're just gonna do that
#MIX is included if it has a secondary breed
#state has to be uppercase converted to symbol to look for full state name using CS gem
        #state = pet["addr_state_code"].parameterize.upcase.to_sym
        #breed = pet["primary_breed"]
#make breed lower case
        #trimmed_breed = breed.downcase.gsub(/^[^a-z0-9\s]/i, '')
        #trimmed_breed = trimmed_breed.tr(' ', '-')
        #@pet_url = "http://www.adoptapet.com/pet/"+pet["pet_id"]+"-"+pet["addr_city"].downcase+"-"+CS.states(:us)[state].downcase+"-"+trimmed_breed
        #@pet_url += "-mix"


        @pet_url = "http://www.adoptapet.com/pet/"+pet["pet_id"]
        @details_hash["#{i}"] = @pet_url
    end
  end

  def about_us
    @aboutus = StaticPage.first.about_us
  end

  def woofs_for_help
    @woofsforhelp = StaticPage.first.woofs_for_help
  end

  def help
    @help = StaticPage.first.help
  end

  def contact_us
    @contactus = StaticPage.first.contact_us
  end

  def foster
    @foster = StaticPage.first.foster
  end

  def donate
    @donate = StaticPage.first.donate
  end

  #Edit GET requests
  def edit_home 
    @spname = "Home"
  end

  def edit_about_us
    @spname = "About Us"
  end

  def edit_woofs_for_help
    @spname = "Woofs for Help"
  end

  def edit_help
    @spname = "Help"
  end

  def edit_contact_us
    @spname = "Contact Us"
  end

  def edit_sidebar
    @spname = "Sidebar"
  end

  def edit_donate
    @spname = "Donate"
  end

  def edit_event
    @spname = "Event"
  end

  def edit_special_event
    @spname = "Special Event"
  end

  def edit_foster
    @spname = "Foster"
  end

  def edit_adopt
    @spname = "Adopt"
  end

  # GET /static_pages
  def index
    @sp = StaticPage.first
  end

  # GET /static_pages/new
  def new
    @static_page = StaticPage.new
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
    @static_page = StaticPage.new(static_page_params)
    respond_to do |format|
      if @static_page.save
        format.html { redirect_to @static_page }
        format.json { render :show, status: :created, location: @static_page }
      else
        format.html { render :new }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /static_pages/1
  # PATCH/PUT /static_pages/1.json
  def update
    @sp = @static_page
    respond_to do |format|
      if @static_page.update(static_page_params)
        flash[:success] = "Page updated successfully."
        format.html { redirect_to static_pages_path }
        format.json { render :show, status: :ok, location: static_pages_path }
      else
        flash[:error] = "Page cannot be blank."
        format.html { redirect_to static_pages_path }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
    respond_to do |format|
      format.html { redirect_to root_path } 
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_page
      @static_page = StaticPage.find(params[:id])
    end
    
    def set_sp
      @sp = StaticPage.first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_page_params
      params.fetch(:static_page, {})
      params.require(:static_page).permit(:about_us, :contact_us, :help, :sidebar, :home_block_one, :woofs_for_help, :event, :special_event, :foster, :donate, :adopt)
    end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_footer.html.erb
<% if logged_in? %>
    <% if admin? %>
        <nav class="navbar fixed-bottom navbar-light">
            <ul class="nav navbar-nav">
                <li class="nav-item">
                    <%= link_to "Profile", user_path(current_user) %>|<%= link_to "Settings", edit_user_path(@current_user) %>|<%= link_to "Users Management", users_path %>|<%= link_to "Edit Pages", static_pages_path %>|<%= link_to "News Management", news_management_path %>|<%= link_to "Logout", logout_path, method: "delete" %>
                </li>
            </ul>
        </nav>
    <% elsif moderator? %>
        <nav class="navbar fixed-bottom navbar-light">
            <ul class="nav navbar-nav">
                <li class="nav-item">
                    <%= link_to "Profile", user_path(current_user) %>|<%= link_to "Settings", edit_user_path(@current_user) %>|<%= link_to "Users Management", users_path %>|<%= link_to "News Management", blogs_path%>|<%= link_to "Logout", logout_path, method: "delete" %>
                </li>
            </ul>
        </nav>
    <% else %>
        <nav class="navbar fixed-bottom navbar-light">
            <ul class="nav navbar-nav">
                <li class="nav-item">
                    <%= link_to "Profile", user_path(current_user) %>|<%= link_to "Settings", edit_user_path(@current_user) %>|<%= link_to "Logout", logout_path, method: "delete" %>
                </li>
            </ul>
        </nav>
    <% end %>
<% else %>
    <nav class="navbar fixed-bottom navbar-light" visibility="true">
        <ul class="nav navbar-nav">
            <li class="nav-item">
                <%= link_to "Login", login_path %>
            </li>
        </ul>
    </nav>
<% end %>

app/views/static_pages/_form.html.erb
<div class="row">
<%= form_for(@sp) do |f| %>
  <% if @sp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sp.errors.count, "error") %> prohibited the '<%=@spname%>' page from being saved:</h2>

      <ul>
      <% @sp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-lg-12">
    <%= f.label @spname %>
    <% if @spname == "Home" %>
        <%= f.cktext_area :home_block_one, class: "form-control", ckeditor: {language: "us" } %>
    <% elsif @spname == "Event" %>
        <%= f.cktext_area :event, class: "form-control", ckeditor: {language: "us" } %>
    <% elsif @spname == "Special Event" %>
        <%= f.cktext_area :special_event, class: "form-control", ckeditor: {language: "us" } %>
    <% elsif @spname == "Adopt" %>
        <%= f.cktext_area :adopt, class: "form-control", ckeditor: {language: "us" } %>
    <% elsif @spname == "Foster" %>
        <%= f.cktext_area :foster, class: "form-control", ckeditor: {language: "us" } %>
    <% elsif @spname == "Donate" %>
        <%= f.cktext_area :donate, class: "form-control", ckeditor: {language: "us" } %>
    <% elsif @spname == "Contact Us" %>
        <%= f.cktext_area :contact_us, class: "form-control", ckeditor: {language: "us" } %>
    <% elsif @spname == "About Us" %>
        <%= f.cktext_area :about_us, class: "form-control", ckeditor: {language: "us" } %>
    <% elsif @spname == "Woofs for Help" %>
        <%= f.cktext_area :woofs_for_help, class: "form-control", ckeditor: {language: "us" } %>
    <% elsif @spname == "Help" %>
        <%= f.cktext_area :help, class: "form-control", ckeditor: {language: "us" } %>
    <% elsif @spname == "Sidebar" %>
        <%= f.cktext_area :sidebar, class: "form-control", ckeditor: {language: "us" } %>
    <% end %>
     <div class="actions" style="margin-top: 5px;">
            <%= f.submit "Update" %>
     </div>
  </div>
<% end %>
</div>

app/views/static_pages/_sidebar.html.erb
<%= raw(@sidebar) %>

app/views/static_pages/contact_us.html.erb
<% title "Contact Us - Real Good Dog Rescue" %>
<%= raw(@contactus) %>
<h1>RGDR Contact Form</h1>
<%= form_tag("/contact", { method: :post }) do %>
    <% if @errors %>
        <div id="error_explanation">
        <h2><%= @errors.count %> errors prohibited this form from being saved:</h2>

          <ul>
          <% @errors.each do |key, message| %>
            <li><b><%= key %>: </b><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    <div class="row">
        <div class="col-lg-7">
            <%= label_tag "First Name", nil, class: "required" %>
            <%= text_field_tag "first_name", params[:first_name], class: "form-control" %>

            <%= label_tag "Last Name", nil, class: "required" %>
            <%= text_field_tag "last_name", params[:last_name], class: "form-control" %>

            <%= label_tag "Email Address", nil, class: "required" %>
            <%= email_field_tag "email", params[:email], class: "form-control" %>
            
            <%= label_tag "Phone Number", nil, class: "required" %>
            <%= text_field_tag "phone_number", params[:phone_number], class: "form-control" %>
            
            <%= label_tag "Your Message", nil, class: "required" %>
            <%= text_area_tag "message", params[:message], class: "form-control" %>
        </div>
    </div>
    <div class="actions" style="margin-top: 5px;">
        <%= submit_tag "Submit" %>
    </div>
<% end %>

app/views/static_pages/donate.html.erb
<% title "Donate - Real Good Dog Rescue" %>
<%= raw(@donate) %>

app/views/static_pages/edit_donate.html.erb
<% title "Editing #{@spname} - Real Good Dog Rescue" %>
<h1><%= "Editing #{@spname}" %></h1>
<%= render 'form' %>

app/views/static_pages/edit_foster.html.erb
<% title "Editing #{@spname} - Real Good Dog Rescue" %>
<h1><%= "Editing #{@spname}" %></h1>
<%= render 'form' %>

app/views/static_pages/edit_home.html.erb
<% title "Editing #{@spname} - Real Good Dog Rescue" %>
<h1><%= "Editing #{@spname}" %></h1>
<%= render 'form' %>

app/views/static_pages/edit_special_event.html.erb
<% title "Editing #{@spname} - Real Good Dog Rescue" %>
<h1><%= "Editing #{@spname}" %></h1>
<%= render 'form' %>

app/views/static_pages/edit_woofs_for_help.html.erb
<% title "Editing #{@spname} - Real Good Dog Rescue" %>
<h1><%= "Editing #{@spname}" %></h1>
<%= render 'form' %>

app/views/static_pages/foster.html.erb
<% title "Foster - Real Good Dog Rescue" %>
<%= raw(@foster) %>

app/views/static_pages/home.html.erb
<% title "Real Good Dog Rescue" %>
<%= render partial: "home_block_one" %>
<h1 align="center">Adoptable Pets at Real Good Dog Rescue</h1>
<div class="row" align="center" style="display:block;">
    <% pointer_i = 0 %>
    <% @pets.each_with_index do |pet, i| %>
        <% if (i % 3 == 0) %>
            <div class="row">
            <% pointer_i = i %>
        <% end %>
        <% pointer_i += 1%>
        <div class="col-lg-4 pet-margin">
            <div class="pet-container">
                <h1 align="center">
                    <%= link_to "#{pet["pet_name"].capitalize}", "#{@details_hash["#{i}"]}", target: "_blank", class: "pet_name" %>
                </h1>
                <%= link_to image_tag(pet["large_results_photo_url"], style: "margin: 0; display: block; padding-bottom: 10px;"), "#{@details_hash["#{i}"]}" %>
            </div>
        </div>
        <% if pointer_i == (@pets.size)%>
            <% if (pointer_i % 3 == 1) %>
               <div class="col-lg-4"></div> 
               <div class="col-lg-4"></div> 
               </div>
            <% elsif (pointer_i % 3 == 2) %>
               <div class="col-lg-4"></div> 
               </div>
            <% end %>
        <% else %>
            <% if (pointer_i % 3== 0) %>
                </div>
            <% end %>
        <% end %>
    <% end %>
</div>

app/views/static_pages/index.html.erb
<% title "Edit Pages - Real Good Dog Rescue" %>
<h1>Editable Pages</h1>
<div class="bs-callout bs-callout-primary">
    <h4 class="card-title">Home:</h4>
    <p class="card-text"><%= raw(@sp.home_block_one) %></p>
    <%= link_to "Edit", home_edit_path, class: "btn btn-primary" %>
</div>

<div class="bs-callout bs-callout-primary">
    <h4 class="card-title">Sidebar:</h4>
    <p class="card-text"><%= raw(@sp.sidebar) %></p>
    <%= link_to "Edit", edit_sidebar_path, class: "btn btn-primary" %>

</div>

<div class="bs-callout bs-callout-primary">
    <h4 class="card-title">Event:</h4>
    <p class="card-text"><%= raw(@sp.event) %></p>
    <%= link_to "Edit", event_edit_path, class: "btn btn-primary" %>

</div>

<div class="bs-callout bs-callout-primary">
    <h4 class="card-title">Special Event:</h4>
    <p class="card-text"><%= raw(@sp.special_event) %></p>
    <%= link_to "Edit", special_event_edit_path, class: "btn btn-primary" %>

</div>

<div class="bs-callout bs-callout-primary">
    <h4 class="card-title">Adopt:</h4>
    <p class="card-text"><%= raw(@sp.adopt) %></p>
    <%= link_to "Edit", adopt_edit_path, class: "btn btn-primary" %>

</div>

<div class="bs-callout bs-callout-primary">
    <h4 class="card-title">Foster:</h4>
    <p class="card-text"><%= raw(@sp.foster) %></p>
    <%= link_to "Edit", foster_edit_path, class: "btn btn-primary" %>

</div>

<div class="bs-callout bs-callout-primary">
    <h4 class="card-title">Donate:</h4>
    <p class="card-text"><%= raw(@sp.donate) %></p>
    <%= link_to "Edit", donate_edit_path, class: "btn btn-primary" %>

</div>

<div class="bs-callout bs-callout-primary">
    <h4 class="card-title">About Us:</h4>
    <p class="card-text"><%= raw(@sp.about_us) %></p>
    <%= link_to "Edit", about_us_edit_path, class: "btn btn-primary" %>
</div>

<div class="bs-callout bs-callout-primary">
    <h4 class="card-title">Woofs For Help:</h4>
    <p class="card-text"><%= raw(@sp.woofs_for_help) %></p>
    <%= link_to "Edit", woofs_for_help_edit_path, class: "btn btn-primary" %>
</div>

<div class="bs-callout bs-callout-primary">
    <h4 class="card-title">Helpful Info:</h4>
    <p class="card-text"><%= raw(@sp.help) %></p>
    <%= link_to "Edit", help_edit_path, class: "btn btn-primary" %>
</div>

<div class="bs-callout bs-callout-primary">
    <h4 class="card-title">Contact Us:</h4>
    <p class="card-text"><%= raw(@sp.contact_us) %></p>
    <%= link_to "Edit", contact_us_edit_path, class: "btn btn-primary" %>
</div>

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>