config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'sessions/new'

  resources :blogs
  get '/news', to: "blogs#index"
  get '/news/:id', to: "blogs#show", as: "new"
  get '/new_news', to: "blogs#new"
  get '/news/:id/edit', to: "blogs#edit", as: "edit_news"
  put '/news/:id/update', to: "blogs#update"
  get '/news_management', to: "blogs#management"
  post '/news/:id/toggle', to: "blogs#toggle_active"
  resources :static_pages, :only => [:index, :edit, :create, :update]
  get 'home', :to => 'static_pages#home'
  get 'home/edit', :to => 'static_pages#edit_home'
  get 'about_us', :to => 'static_pages#about_us'
  get 'about_us/edit', :to => 'static_pages#edit_about_us'
  get 'woofs_for_help', :to => 'static_pages#woofs_for_help'
  get 'woofs_for_help/edit', :to => 'static_pages#edit_woofs_for_help'
  get 'help', :to => 'static_pages#help'
  get 'help/edit', :to => 'static_pages#edit_help'
  get 'contact_us', :to => 'static_pages#contact_us'
  get 'contact_us/edit', :to => 'static_pages#edit_contact_us'
  post 'contact', to: 'forms#contact'
  get 'foster', to: 'static_pages#foster'
  get 'foster/edit', to: 'static_pages#edit_foster'
  get 'event/edit', to: 'static_pages#edit_event'
  get 'special_event/edit', to: 'static_pages#edit_special_event'
  get 'donate', to: 'static_pages#donate'
  get 'donate/edit', to: 'static_pages#edit_donate'
  get 'adopt/edit', to: 'static_pages#edit_adopt'
  get 'edit_sidebar', :to => 'static_pages#edit_sidebar'
  resources :events
  get 'special_events', :to => "events#special_events"
  get 'adopt', :to => "forms#adopt"
  post 'send_adoption', :to => "forms#send_adoption"
  resources :users
  get '/user/:id/user_management', to: 'users#hierarchy'
  post '/user/:id/user_management', to: 'users#set_hierarchy'
  post '/users/set_state', to: 'users#set_state'
  get 'confirm_email', to: 'users#confirm_email'
  post '/user/:id/ban', to: 'users#ban', as: 'ban_user'
  resources :comments
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/confirm_email_login', to: 'sessions#confirm_email_login'
  delete '/logout', to: 'sessions#destroy'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :password_managements, only: [:create, :edit, :update]
  root to: 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    after_create :confirmation_token
    has_many :blogs

    attr_accessor :remember_token, :password_confirmation, :current_password, :reset_token
    VALID_AGE_REGEX = /\A[0-9][0-9]?[0-9]?\Z/
    VALID_EMAIL_REGEX = /\A\w+\@\w+\.\w+\Z/ #remember to trim whitespace when validating
    VALID_ZIP_REGEX = /\A\d{5}(-\d{4})?\Z/
    VALID_PHONE_REGEX = /\A\(?\d{3}\)?\-?\d{3}\-?\d{4}\Z/
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :age, presence: true, format: { with: VALID_AGE_REGEX }
    validates :email, uniqueness: true, presence: true, format: { with: VALID_EMAIL_REGEX }
#address
    validates :address_line_one, presence: true 
    validates_length_of :address_line_one, :maximum => 25

    validates_length_of :address_line_two, :maximum => 25
    validates :city, presence: true 
    validates :state, presence: true #validate state from a list
    validates :zip, presence: true, format: { with: VALID_ZIP_REGEX }
    validates :phone, presence: true, format: { with: VALID_PHONE_REGEX }
    validates :phone, length: { is: 10 }
    validates :hierarchy, presence: true, numericality: { :less_than_or_equal_to => 2, :greater_than => -1 }
    validates :banned, inclusion: { in: [true, false] }
    validates :subscribed, inclusion: { in: [true, false] }

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    validates :password, confirmation: true

    def remember
        self.remember_token = User.new_token
        self.update_attribute(:remember_digest, User.digest(remember_token))
    end

    def confirm(user, token)
        if !user.confirmed? && token == user.confirm_token
            self.update_attribute(:confirm_token, nil)
            self.update_attribute(:email_confirmed, true)
            true
        end
    end

    def confirmed?
        return false if !email_confirmed
    end

    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def authenticated_reset?(token)
        return false if reset_digest .nil?
        BCrypt::Password.new(reset_digest).is_password?(token)
    end


    def forget
        update_attribute(:remember_digest, nil)
    end
    
    def full_name
        "#{self.first_name} #{self.last_name}"
    end

    def format_phone
        "(" + self.phone[0..2] + ")" + self.phone[3..5] + "-" + phone[6..9]
    end

    def admin?
        self.hierarchy == 0
    end

    def mod?
        self.hierarchy == 1
    end

    def member?
        self.hierarchy == 2
    end

    def at_least_mod?
        self.hierarchy < 2
    end

    def create_reset_digest
        self.reset_token = User.new_token
        update_attribute(:reset_digest, User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end

    def password_reset_expired?
        self.reset_sent_at < 2.hours.ago
    end

    class << self

        def digest(string)
            cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
            BCrypt::Password.create(string, cost: cost)
        end


        def new_token
            SecureRandom.urlsafe_base64
        end
    end

    private
        
        def confirmation_token
            if self.confirm_token.blank? && !self.email_confirmed
                self.update_attribute(:confirm_token, SecureRandom.urlsafe_base64.to_s)
            end
        end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  include ApplicationHelper
  before_action :set_user, only: [:show, :edit, :update, :destroy, :ban]
  before_action :set_user_state, only: [:edit, :update] 
  before_action :same_user, only: [:edit, :show, :update]
  before_action :no_admin_prevention, only: [:ban, :hierarchy, :set_hierarchy]
  before_action :has_access, only: [:edit, :show, :update]
  before_action :has_access_admin, only: [:hierarchy, :set_hierarchy, :destroy]
  before_action :has_access_moderator, only: [:ban, :index]

  # GET /users
  # GET /users.json
  def index
    @users = User.where(banned: false).order(first_name: :desc, last_name: :desc)
    @banned_users = User.where(banned: true).order(first_name: :desc, last_name: :desc)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    states = CS.states(:us)
    logger.info states.inspect
    @states = []
    @cities = CS.cities(:ak, :us)
    states.each do |k, v|
        @states.push k
    end
  end

  def set_state
    state = params[:selected_state]
    @cities = CS.cities(state, :us)
    logger.info @cities.inspect
    respond_to do |format|
        format.json { render json: @cities }
    end
  end   

  # GET /users/1/edit
  def edit
    @user = User.find_by_id(params[:id])
  end

  def hierarchy 
    @user = User.find_by_id(params[:id])
  end

  def set_hierarchy 
    @user = User.find_by_id(params[:id])
    case params[:user_h]
        when "admin"
            hierarchy = 0
        when "moderator"
            hierarchy = 1
        when "member"
            hierarchy = 2
        else
            hiearchy = -1
    end

    if @user.update_attribute(:hierarchy, hierarchy)
        flash[:success] = "#{@user.full_name} power was set to: #{params[:user_h]}"
        redirect_to @user
    else
        flash[:error] = "You must select an option."
        redirect_to "/user/#{@user.id}/user_management"
    end
    
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    #Set state/cities variables
    states = CS.states(:us)
    state = user_params[:state]
    @states = []
    states.each do |k, v|
        @states.push k
    end

    @cities = CS.cities(state, :us)
    p = @user.phone
    #trim unwanted values
    p = p.tr('()-', '') 
    #trim whitespace
    p = p.tr(' ', '')
    @user.phone = p
    #0 = admin; 1 = moderator; 2 = member
    #default: 2
    @user.hierarchy = 2
    if user_params[:subscribed] && user_params[:subscribe] == 'true'
        @user.subscribed = true
    else
        @user.subscribed = false
    end
    #user must confirm email before login in
    @user.email_confirmed = 0
    @user.banned = 0
    respond_to do |format|
      if @user.save
        UserMailer.welcome_email(@user).deliver
        flash[:success] = "Your account was created successfully! Please confirm your email address to login."
        format.html { redirect_to login_path }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def ban
    if @user.banned
        @user.update_attribute(:banned, false)
        flash[:warning] = "#{@user.full_name} has been unbanned."
        redirect_to users_path
    else
        @user.update_attribute(:banned, true)
        flash[:warning] = "#{@user.full_name} has been banned."
        redirect_to users_path
    end
  end

  def confirm_email
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    #trim ()- characters from phone if entered
    p = @user.phone
    digits_p = p.tr('()-', '') 
    trimmed_p = digits_p.tr(' ', '')
    params[:user][:phone] = trimmed_p
    logger.info params.inspect
    respond_to do |format|
      if @user.authenticate(params[:user][:password]) && @user.update(user_params) 
        flash[:success] = "User updated successfully."
        format.html { redirect_to @user } 
        format.json { render :show, status: :ok, location: @user }
      elsif @user.errors.empty?
        flash.now[:error] = "Incorrect password."
        format.html { render :edit }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    respond_to do |format|
      flash[:info] = "User deactivated"
      format.html { redirect_to users_url } 
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find_by_id(params[:id])
      if !@user
          redirect_to root_path
          flash[:error] = "We could not find that user."
      end
    end

    def set_user_state
        @user = User.find(params[:id])
        states = CS.states(:us)
        @states = []
        @cities = CS.cities(@user.state, :us)
        states.each do |k, v|
            @states.push k
        end
    end

    def no_admin_prevention
        if current_user
            if (current_user.id == params[:id].to_i || (current_user.hierarchy > User.find_by_id(params[:id]).hierarchy))
                flash[:info] = "You cannot do that."
                redirect_to users_path
            else
                true
            end
        end

    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      #params.fetch(:user, {})
      params.require(:user).permit(:first_name, :last_name, :age, :email, :address_line_one, :address_line_two, :city, :password, :password_confirmation, :banned, :state, :subscribed, :zip, :phone)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<% title "Edit Profile - Real Good Dog Rescue" %>
<div class="row">
    <div class="col-lg-12">
        <%= form_for(@user) do |f| %>
          <% if @user.errors.any? %>
            <div class="row">
                <div class="col-lg-12">
                    <div id="error_explanation">
                      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

                      <ul>
                      <% @user.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                      </ul>
                    </div>
                </div>
            </div>
          <% end %>
        <div class="row">
            <div class="col-lg-6">
                  <%= f.label :first_name %>
                  <%= f.text_field :first_name, class: "form-control" %>
                  <%= f.label :last_name %>
                  <%= f.text_field :last_name, class: "form-control" %>
                  <%= f.label :email %>
                  <%= f.text_field :email , class: "form-control" %>
                  <%= f.label :age %>
                  <%= f.text_field :age, class: "form-control" %>
                  <%= f.label :phone%>
                  <%= f.text_field :phone, class: "form-control" %>
                  <%= f.label :password %>
                  <%= f.password_field :password, class: "form-control" %>
                  <div class="actions" style="margin-top: 10px;">
                    <%= f.submit %>
                  </div>
              </div>
            <div class="col-lg-6">
                  <%= f.label :adress_line_one %>
                  <%= f.text_field :address_line_one, class: "form-control" %>
                  <%= f.label :adress_line_two %>
                  <%= f.text_field :address_line_two, class: "form-control" %>
                  <%= f.label :state %>
                  <%= f.collection_select :state, @states, :to_s, :to_s, { include_blank: false } , {:class => "form-control", id: "states" } %>
                  <%= f.label :city %>
                  <%= f.collection_select :city, @cities, :to_s, :to_s, { include_blank: false }, { class: "form-control", id: "cities" } %>
                  <%= f.label :zip %>
                  <%= f.text_field :zip, class: "form-control" %>
                  <%= f.label "Subscribed from Newsfeed" %>
                  <%= f.check_box :subscribed, checked_value: true, unchecked_value: false %>

            </div>
        </div>
        <% end %>
        <div class="col-lg-2"></div>
        <script>
            $(document).ready(function() {
                function change_select(data){
                    $('#cities').empty();
                    for(var i = 0; i < data.length; i++){
                        $('#cities').append("<option value=\""+data[i]+"\">"+data[i]+"</option>");
                    }
                };

                $('#states').on('change', function(){
                    state = $('#states').val();
                    $.post("/users/set_state", {selected_state: state}, function(data, status){
                        if(status =="success"){
                            change_select(data);
                        }
                    });
                });
            });
        </script>
</div>

app/views/users/_form.html.erb
<% title "Registration - Real Good Dog Rescue" %>
<div class="row">
    <div class="col-lg-12">
        <%= form_for(@user) do |f| %>
              <% if @user.errors.any? %>
                <div class="row">
                    <div class="col-lg-12">
                        <div id="error_explanation">
                          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

                          <ul>
                          <% @user.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                          <% end %>
                          </ul>
                        </div>
                    </div>
                </div>
          <% end %>
            <div class="row">
                <div class="col-lg-6">
                          <%= f.label :first_name, class: "required" %>
                          <%= f.text_field :first_name, class: "form-control" %>
                          <%= f.label :last_name, class: "required" %>
                          <%= f.text_field :last_name, class: "form-control" %>
                          <%= f.label :email, class: "required" %>
                          <%= f.text_field :email , class: "form-control" %>
                          <%= f.label :age, class: "required" %>
                          <%= f.text_field :age, class: "form-control" %>
                          <%= f.label :phone, class: "required" %>
                          <%= f.text_field :phone, class: "form-control" %>
                          <%= f.label :password, class: "required" %>
                          <%= f.password_field :password, class: "form-control" %>
                          <%= f.label :password_confirmation, class: "required" %>
                          <%= f.password_field :password_confirmation, class: "form-control" %>
                          <div class="actions" style="margin-top: 10px;">
                            <%= f.submit %>
                          </div>
                </div>
                <div class="col-lg-6">
                          <%= f.label :adress_line_one, class: "required" %>
                          <%= f.text_field :address_line_one, class: "form-control" %>
                          <%= f.label :adress_line_two %>
                          <%= f.text_field :address_line_two, class: "form-control" %>
                          <%= f.label :state, class: "required" %>
                          <%= f.collection_select :state, @states, :to_s, :to_s, { include_blank: false } , {:class => "form-control", id: "states" } %>
                          <%= f.label :city, class: "required" %>
                          <%= f.collection_select :city, @cities, :to_s, :to_s, { include_blank: false }, { class: "form-control", id: "cities" } %>
                          <%= f.label :zip, class: "required" %>
                          <%= f.text_field :zip, class: "form-control" %>
                          <%= f.label "Subscribe to News letter" %>
                          <%= f.check_box :subscribed, {}, true, false %>
                </div>
            </div>
        <% end %>
    </div>
</div>
        <script>
            $(document).ready(function() {
                function change_select(data){
                    $('#cities').empty();
                    for(var i = 0; i < data.length; i++){
                        $('#cities').append("<option value=\""+data[i]+"\">"+data[i]+"</option>");
                    }
                };

                $('#states').on('change', function(){
                    state = $('#states').val();
                    $.post("/users/set_state", {selected_state: state}, function(data, status){
                        if(status =="success"){
                            change_select(data);
                        }
                    });
                });
            });
        </script>

app/views/users/_user.html.erb
<% title "#{@user.full_name} - Real Good Dog Rescue" %>
<div class="card">
    <div class="card-header">
        <h3>Details<h3>
    </div>
    <div class="card-block">
        <h4 class="card-title"><%= @user.full_name %> -
        <% if (@user.hierarchy == 0) %>
            Admin</h4>
        <% elsif (@user.hierarchy == 1) %>
            Moderator</h4>
        <% else %>
            Member</h4>
        <% end %>

        <h5>Email: <%=@user.email%></h5>
        <h5>Age: <%=@user.age%></h5>
        <h5>Address Line 1: <%=@user.address_line_one%></h5>
        <% if !@user.address_line_two.blank? %>
            <h5>Address Line 2: <%=@user.address_line_two%></h5>
        <% end %>
        <h5>City: <%=@user.city%></h5>
        <h5>State: <%=@user.state%></h5>
        <h5>ZIP: <%=@user.zip%></h5>
        <h5>Phone: <%=@user.format_phone%></h5>
        <h5>Subscribed to Newsletter: <%=@user.subscribed ? "Yes":"No" %></h5>
    </div>
</div>

app/views/users/confirm_email.html.erb
<% title "Confirm Email - Real Good Dog Rescue" %>
<div class="row">
    <div class="col-lg-5">
        <h2>Confirm Email</h2>
        <%= form_for(:session, url: confirm_email_login_path) do |f| %>
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control" %>
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>
            <%= f.hidden_field "confirm_token", value: params[:confirm_token] %>
            <%= f.label :remember_me, class: "checkbox inline" do %>
            <%= f.check_box :remember_me %>
            <% end %>
            <span>Remember me?</span>
            <br>
            <%= f.submit "Log in" %>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<% title "Edit Profile - Real Good Dog Rescue" %>
<% if current_user.id == @user.id %>
    <h1>Editing Profile</h1> 
<% else %>
    <h1>Editing <%= "#{@user.first_name} #{@user.last_name}" %></h1>
<% end %>

<%= render 'edit_form' %>

<%= link_to 'Show', @user %> |
<%= link_to "Change Password", edit_password_management_path(@user.id) %> |
<%= link_to 'Back', users_path %> 

app/views/users/hierarchy.html.erb
<h1><%= "Editing #{@user.full_name} Hierarchy" %></h1>
<div class="col-2-lg"></div>
<div class="col-10-lg">
    <div class="form-group">
        <%= form_tag url: "user/#{@user.id}/user_management", as: :post do %>
            <% if @user.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

                  <ul>
                  <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
            <% end %>
            <%= render @user %>
            <div class="form-check">
               <div class="bs-callout bs-callout-danger">
                    <h4>Admin</h4>
                    <%= radio_button_tag "user_h", "admin" %>
                    This will make user able to have access to all features including: Edit Pages, Change user permissions, Create/Edit/Delete blog posts.
               </div>
            </div>
            <div class="form-check">
                <div class="bs-callout bs-callout-info">
                    <h4>Moderator</h4>
                    <%= radio_button_tag "user_h", "moderator" %>
                    This will make user limited to only: Manage users who post comments on blogs.
                </div>
            </div>
            <div class="form-check">
                <div class="bs-callout bs-callout-success">
                    <h4>Member</h4>
                    <%= radio_button_tag "user_h", "member" %>
                    This will make user limited to just browse the website and only being able to post comments blogs or events.
                </div>
            </div>
            <%= submit_tag "Submit" %>
    <% end %>
    </div>
</div>

app/views/users/index.html.erb
<% title "Users - Real Good Dog Rescue" %>

    <%= javascript_include_tag "https://cdn.datatables.net/responsive/2.1.1/js/dataTables.responsive.min.js" %>
    <%= stylesheet_link_tag "https://cdn.datatables.net/responsive/2.1.1/css/responsive.dataTables.min.css" %>
<!--
    <= javascript_include_tag "//cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js" %>
    <= javascript_include_tag "https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap4.min.js" %>
    <= stylesheet_link_tag "https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap4.min.css" %>
-->
        <h1>Listing Users</h1>

        <table id="users_table" class="table table-striped table-bordered users-table" width="100%">
          <thead>
            <tr>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Phone</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.first_name %></td>
                <td><%= user.last_name %></td>
                <td><%= user.email %></td>
                <td><%= user.phone %></td>
                <td><%= link_to 'Profile', user, target: "_blank" %></td>
                <td><%= link_to 'Permissions', "user/#{user.id}/user_management" %></td>
                <td><%= link_to 'Ban User', ban_user_path(user), method: :post %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <h1>Listing Banned Users</h1>
        <table id="banned_users_table" class="table table-striped table-bordered users-table" width="100%">
          <thead>
            <tr>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Phone</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @banned_users.each do |user| %>
              <tr>
                <td><%= user.first_name %></td>
                <td><%= user.last_name %></td>
                <td><%= user.email %></td>
                <td><%= user.phone %></td>
                <td><%= link_to 'Profile', user %></td>
                <td><%= link_to 'Permissions', "user/#{user.id}/user_management" %></td>
                <td><%= link_to 'Unban User', ban_user_path(user), method: :post %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
<script>
$(document).ready(function() {
        $('#users_table').DataTable({
            responsive: true   
        });
        $('#banned_users_table').DataTable({
            responsive: true   
        });
 
        $("#users_table_length").css("color", "white");
        $("#users_table_filter").css("color", "white");
        $("#users_table_paginate").css("color", "white");
        $("#users_table thead").css("background-color", "white");
        $("#users_table tr:odd").css("background-color", "#95A4E6");
        $("#users_table tr").css("color", "black");

        $("#banned_users_table_length").css("color", "white");
        $("#banned_users_table_filter").css("color", "white");
        $("#banned_users_table_paginate").css("color", "white");
        $("#banned_users_table thead").css("background-color", "white");
        $("#banned_users_table tr:odd").css("background-color", "#95A4E6");
        $("#banned_users_table tr").css("color", "black");

} );
</script>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<% title "Profile - Real Good Dog Rescue" %>
<h1><%= @user.full_name %></h1>
<h5>Email: <%=@user.email%></h5>
<h5>Age: <%=@user.age%></h5>
<h5>Address Line 1: <%=@user.address_line_one%></h5>
<% if !@user.address_line_two.blank? %>
    <h5>Address Line 2: <%=@user.address_line_two%></h5>
<% end %>
<h5>City: <%=@user.city%></h5>
<h5>State: <%=@user.state%></h5>
<h5>ZIP: <%=@user.zip%></h5>
<h5>Phone: <%=@user.format_phone%></h5>
<h5>Subscribed: <%= @user.subscribed ? "Yes":"No" %></h5>
<%= link_to 'Edit', edit_user_path(@user) %> | <%= link_to "Change Password", edit_password_management_path %>