config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'sessions/new'

  resources :blogs
  get '/news', to: "blogs#index"
  get '/news/:id', to: "blogs#show", as: "new"
  get '/new_news', to: "blogs#new"
  get '/news/:id/edit', to: "blogs#edit", as: "edit_news"
  put '/news/:id/update', to: "blogs#update"
  get '/news_management', to: "blogs#management"
  post '/news/:id/toggle', to: "blogs#toggle_active"
  resources :static_pages, :only => [:index, :edit, :create, :update]
  get 'home', :to => 'static_pages#home'
  get 'home/edit', :to => 'static_pages#edit_home'
  get 'about_us', :to => 'static_pages#about_us'
  get 'about_us/edit', :to => 'static_pages#edit_about_us'
  get 'woofs_for_help', :to => 'static_pages#woofs_for_help'
  get 'woofs_for_help/edit', :to => 'static_pages#edit_woofs_for_help'
  get 'help', :to => 'static_pages#help'
  get 'help/edit', :to => 'static_pages#edit_help'
  get 'contact_us', :to => 'static_pages#contact_us'
  get 'contact_us/edit', :to => 'static_pages#edit_contact_us'
  post 'contact', to: 'forms#contact'
  get 'foster', to: 'static_pages#foster'
  get 'foster/edit', to: 'static_pages#edit_foster'
  get 'event/edit', to: 'static_pages#edit_event'
  get 'special_event/edit', to: 'static_pages#edit_special_event'
  get 'donate', to: 'static_pages#donate'
  get 'donate/edit', to: 'static_pages#edit_donate'
  get 'adopt/edit', to: 'static_pages#edit_adopt'
  get 'edit_sidebar', :to => 'static_pages#edit_sidebar'
  resources :events
  get 'special_events', :to => "events#special_events"
  get 'adopt', :to => "forms#adopt"
  post 'send_adoption', :to => "forms#send_adoption"
  resources :users
  get '/user/:id/user_management', to: 'users#hierarchy'
  post '/user/:id/user_management', to: 'users#set_hierarchy'
  post '/users/set_state', to: 'users#set_state'
  get 'confirm_email', to: 'users#confirm_email'
  post '/user/:id/ban', to: 'users#ban', as: 'ban_user'
  resources :comments
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/confirm_email_login', to: 'sessions#confirm_email_login'
  delete '/logout', to: 'sessions#destroy'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :password_managements, only: [:create, :edit, :update]
  root to: 'static_pages#home'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body id="background">
      <div class="container">
            <div class="row">
                <div class="col-lg-12 nopadding" style="display: table;">
                    <%= image_tag "RGDR-banner.png", class: "banner" %>
                    <h2 class="banner-h2">Real Good Dog Rescue</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 nopadding">
                    <nav class="navbar navbar-toggleable-md navbar-light">
                      <a class="navbar-brand" href="/"><%= image_tag "rgdr_logo.png", size: "30x30", :class => "image" %></a>
                      <ul class="nav navbar-nav">
                        <li class="nav-item">
                          <%= link_to "Home", root_path, :class => "nav-link" %>
                        </li>
                        <li class="nav-item">
                          <%= link_to "About Us", about_us_path , :class => "nav-link"%>
                        </li>
                        <li class="nav-item">
                          <%= link_to "Upcoming Events", events_path , :class => "nav-link"%>
                        </li>
                        <li class="nav-item">
                          <%= link_to "News", news_path , :class => "nav-link"%>
                        </li>
                        <li class="nav-item">
                          <%= link_to "Special Events", special_events_path, class: "nav-link" %>
                        </li>
                        <li class="nav-item">
                          <%= link_to "Woofs for Help", woofs_for_help_path , :class => "nav-link"%>
                        </li>
                        <li class="nav-item">
                          <%= link_to "Adopt", adopt_path, class: "nav-link" %>
                        </li>
                        <li class="nav-item">
                          <%= link_to "Foster", foster_path, class: "nav-link" %>
                        </li>

                        <li class="nav-item">
                          <%= link_to "Donate", donate_path, class: "nav-link" %>
                        </li>
                      </ul>
                      <ul class="nav navbar-nav float-lg-right">
                        <li class="nav-item">
                          <%= link_to "Helpful Info", help_path , :class => "nav-link"%>
                        </li>
                        <li class="nav-item">
                          <%= link_to "Contact Us", contact_us_path , :class => "nav-link"%>
                        </li>
                      </ul>
                    </nav>
                </div>
            </div>

            
            <div class="row">
                <div class="col-lg-2 nopadding">
                    <div class="jumbotron sidebar">
                        <%= render partial: "static_pages/sidebar" %>
                    </div>
                </div>
                <div class="col-lg-10 nopadding">
                    <div class="jumbotron content">
                        <%= flash_messages %>
                        <%= yield %>
                    </div>
                    <%= render partial: "static_pages/footer" %>
                </div>
            </div>
        </div>
      </div>

    </body>
    <footer class="cpr-ftr" align="center">
            <%= render partial: "static_pages/copyright_footer" %>
    </footer>
</html>